service: skeinmaster-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  baseAdd:
    handler: src/endpoints/base/add.add
    events:
      - httpApi:
          path: /base/add
          method: post

resources:
  # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: baseTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local
