service: skeinmaster-api
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  baseAdd:
    handler: src/endpoints/base.add
    events:
      - httpApi: { path: /base/add, method: post }
  baseGet:
    handler: src/endpoints/base.get
    events:
      - httpApi: { path: /base/get, method: get }

resources: {}
custom: {}

plugins:
  - serverless-esbuild
  - serverless-offline
