service: skeinmaster-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  baseAdd:
    handler: src/endpoints/base.add
    events:
      - httpApi: { path: /base/add, method: post }
  baseGet:
    handler: src/endpoints/base.get
    events:
      - httpApi: { path: /base/get, method: get }

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: baseTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local
